### ISSUE TITLE
Very good.

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [AsfendTheMVP/Colosseum#1]
How can I get the list with movies in my browser or via postman?
I tried this:

http://colosseum.somee.com/api/NowPlayingMovies/ApiKeyd3ee07e6-db27-4dde-858c-ec53232a1dba

But nothing works.

**Comment by AsfendTheMVP** [comment]
Hi @andersonvieiragomeslopes  I've explained this in my course.
Kindly follow the course to make this application.
Here's the link of this course
[Click Here ](https://www.udemy.com/build-real-world-application-with-xamarin-forms-part-3/?couponCode=G_REALWORLD3)

**Comment by andersonvieiragomeslopes** [comment]
No, I asked a simple and objective question to evaluate what I could buy, but forget it.

**Comment by rraraoz** [comment]
Hello, I have gone through the whole course and I am getting a null reference when pulling the data via api. The url's for example, http://colosseum.somee.com/api/NowPlayingMovies, http://colosseum.somee.com/api/UpComingMovies do not return data.  While looking into this issue I discovered that there is a dns error with the domain name.  Can you please help?

**I am using the following URL**
http://colosseum.somee.com/api/NowPlayingMovies?ApiKey=8e75a7f2-2b51-4360-b684-a14b1b233570

**Postman Returns the following JSON**
<html><head><meta http-equiv="refresh" content="0;url=http://dnserrorassist.att.net/search/?q=http://colosseum.somee.com%2Fapi%2FNowPlayingMovies&t=0&bc="/></head><body><script type="text/javascript">window.location="http://dnserrorassist.att.net/search/?q="+escape(window.location)+"&r="+escape(document.referrer)+"&t=0&bc=";</script></body></html>

Thank you,
-Remigio
